# Generated by Django 5.2.7 on 2025-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('brand', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('normal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oferta', models.BooleanField(blank=True, null=True)),
                ('categoria1', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('categoria2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('datetime', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('atributos', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Atributos', max_length=100, null=True)),
                ('sin_stock', models.BooleanField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('ahorro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ahorro_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('kilo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgProductosRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('brand', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=4000, null=True)),
                ('normal_price', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('low_price', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('high_price', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('oferta', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('categoria1', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=4000, null=True)),
                ('categoria2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=4000, null=True)),
                ('datetime', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('atributos', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Atributos', max_length=4000, null=True)),
                ('sin_stock', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('page', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('ahorro', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('ahorro_percent', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('kilo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'stg_Productos_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad_vendida', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
            ],
            options={
                'db_table': 'Ventas',
                'managed': False,
            },
        ),
    ]
